CC = clang

# Make sure to use the full CFLAGS before turning in. Uncomment this for lax
# checking during development, if you need to.
CFLAGS = -Wall -Wpedantic -Werror -Wextra


all: midterm

midterm: midterm.c
	$(CC) $(CFLAGS) midterm.c -o midterm
